// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Hendrix_Map_Zoom","status":false,"description":"Zoom your map. This plugin is compatible with all Sang Hendrix plugins.","parameters":{"mapZoomValue":"2.0","pixelateGame":"false"}},
{"name":"QuestMenuMZ","status":false,"description":"Отдельное меню для заданий (предметов с тегом <quest>)","parameters":{"Command Name":"Задания"}},
{"name":"CoopPeer","status":true,"description":"v1.0 Простая синхронизация 2 игроков через PeerJS.","parameters":{}}
];
